apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: steward-tls-cert
spec:
  secretName: steward-tls-cert
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging
  usages:
  - server auth
