apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: steward
  app.kubernetes.io/name: steward
resources:
- certificate.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
