apiVersion: v1
kind: PersistentVolume
metadata:
  name: drawbridge-staging
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azureblob-fuse-premium
  mountOptions:
    - -o allow_other
    - --file-cache-timeout-in-seconds=120
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    volumeHandle: drawbridge-staging-volume
    volumeAttributes:
      containerName: drawbridge-staging
    nodeStageSecretRef:
      name: azure-storage-account-profianservicesstaging
      namespace: default

