apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- signingkey.yaml
- pdb.yaml
- ../../base/steward
namespace: steward-production
patches:
- patch-certificate.yaml
- patch-deployment.yaml
- patch-ingress.yaml
