apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: signingkey
  namespace: steward-production
spec:
  encryptedData:
    tls.key: AgBn1JSBwaVPRtLSE05vFe5/A4rmgcFX3jdtdTg3Cx/VcK7W0xzy752+tvOn3XZxJBbAej2/Y2ZNV1u3gxQWOUvao/xx3mNFibyNeMI191jb6cWJb1L5yvnIeg4/itI9yGtyIoeEV63fCrcScgiFFdHoNEfsK2+HCCMavOHgZEdgInTUZYCLlG7Q5dAH8v0P54WiEy40xkKZf5XMg7h2FWx0Pk9qILnnRcTC4B2ROPFT7cMXqjrjbtbBiTcibkc2Bmx8B+zbMOlM6CaJxUsMbD5Xi4L+Weir4kHo5HOQc44NtKWeD/40iDrYjoQFNZAFFrgCF32NyI4LlrnPUsNKdygFfquCp1VOgiHFT1WlVrisaZP8SJEWxH3ZJ4bZ/QpA71kIvdYhVPlduAFbax0MjgYKNwpbvpQTj0e68xHqmyb+QUK74aqI0cQpdbi8oMTNsUB9Ga/QXP8nt+5ELTyh7nThtqHeIDx2YLNR6nuJyKbpJBwnXMfMENqqKltntTM1uodEv4KJDQ5ZzLy+KBYmTQUdabRBvoZLSY1ijQ0yS7afGyhRps8RSSLaKRUw7bNzWQnSzuHu4TmQEk9g64/emg1qtFj0/vwfS6yi3OsLFN1X3POvnpiog3gH9mCtq7/MA3cmrpX2FKwq1/BXzXA9EkyEqQno/PaUkMCdzcUUBUAz4sEMD1vIu2pJiT90WWKJujG0Z3GHq0MHgHTTjYKHaCbJeBO5qyoIrRyPq9qTHtAYL5nL9ush1nqnp+/+7KSGfhWdAzRR5vu9lKPnhhD+R+9nkP0wo0jbFDknou5sAoFvsxCfg1kPkj+B5NZX2iZLmHlLuto2zTUZP+3ipuBdjG9BFPQW7YLTuvYkPfTxh6aSd+MpcSsKdynEJz7xdcdk+u3B352z1uizPDUDNWpue/GGI4AJy9QJvMk1QwIKVovuIOREcWjub+AGcpjcmcbGqPCuQ/Ot8exogShX5o4oWcz6zYOgonswcOAxxyGk0dWrTvGfihcJCLfVtBuRPVZcZ/ZR
  template:
    metadata:
      name: signingkey
      namespace: steward-production
    type: kubernetes.io/tls
    data:
      tls.crt: |-
        -----BEGIN CERTIFICATE-----
        MIICIzCCAcigAwIBAgIUM3CEAbnktQ+pCNw4vGkcm2vvKVYwCgYIKoZIzj0EAwIw
        UzELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
        DAdSYWxlaWdoMRkwFwYDVQQDDBBQcm9vZiBvZiBDb25jZXB0MB4XDTIyMDcxOTE2
        NTM1OFoXDTIzMDcxOTE2NTM1OFowUzELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5v
        cnRoIENhcm9saW5hMRAwDgYDVQQHDAdSYWxlaWdoMRkwFwYDVQQDDBBQcm9vZiBv
        ZiBDb25jZXB0MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEucTTj2v9QYP3S+PS
        6VT8S+Zt4HA2O53d5edhBz62XZivS3oAsWCbgKpIbi/LDh6l6X+zTZ2LU+UTzu61
        Qyw0FaN6MHgwDwYDVR0TAQH/BAUwAwEB/zALBgNVHQ8EBAMCAQYwOQYJYIZIAYb4
        QgENBCwWKlByb2ZpYW4gYXR0ZXN0YXRpb24gc2VydmljZSBDQSBjZXJ0aWZpY2F0
        ZTAdBgNVHQ4EFgQUYOwCTzd04rKqwVTbmXuDkoxZ8BAwCgYIKoZIzj0EAwIDSQAw
        RgIhAPl1ykkPK3b3K60ONCGHyXEXux/Mwap/pZHs2aUBQVrEAiEApNUqk/Vv4EZv
        Gf2dKoQ0iLMS0FJ9LSJlXhDWxlPoN7I=
        -----END CERTIFICATE-----
