apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
spec:
  releaseName: sealed-secrets
  targetNamespace: kube-system
  chart:
    spec:
      chart: sealed-secrets
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
      version: "2.7.x"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    service:
      type: NodePort
