apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gchat-notification
  namespace: flux-system
spec:
  encryptedData:
    address: AgA2vdjLncXQz5jJK3GkKoix7aHgqqBE4+U0ezjnm6avcluaGuEunc0UnXZMySLVl6Wj+icf+J3k5vA+SCIQtVfoWnn4vZ1ZHhUlrwWCYnllZt8VPIBy7jX8TwRWs3RYTA5N/kBUxDJ7TssKdB78Ac3E6EhUIRa2F00MyU6ZaxwKVH0V4nkXcVCwWjX8kSJUKfGOfRYYpGdGdnCQ/p4r8rmyWlLoLP0HHCqRcGWweFo509U4xvBqLvgyaT4aGzkXj3b84hw1XeH1M2C4BWAIHxwV+nqNKI9M6E7T3cUATirfHBQMk9/kBPdbn4RJqCT1VolwfVm19scx/YCbZgP3f9JRpjvuoVbD0EGM9KHbYCNcPXu7zlREbDBAVb+J/Jem9hNb5OfxnC/YtpR7/t+mTfOr2Wv9NfsjsGa/rQYP2haRm4+8qAjeZUzabOJ542U+6BZnesz7QerldpRo8AT/aiSTSFyMkePIATi89EMVAsBQ+PAf9X8AevVcsMFTFlX3PfMrzxYRe2+22jwJuC2x2XA2+iD+QI1n5dHvKlXvagTX1iVcZRG1NqFIR7NnQTynU0IX7aXpU0EvrSHYX0qpvYM8ym8ymjqHt0ugk/ZM41Iq4sFQmnYPYcVftFQ6CPdGV7OzalT3IbhrTzGpCdRY7go/kiMBfGSrK/MLipz2EOWDhVOBgJiDyzQk/bd0iOkSKaYwEqJ/CVx4teTc/sw7qkdI2CM9mMA4E1qVa0YYfZR+PswjT/TXP6dgdjuqYhD9dIczVm04BRQvNiE2oK449qdRc0wThGo/x7Rgt2co5I3TorLE8RpDT0H6nuUXe/5AqCJ/yKdPig47Pf1ziWMSiwo3KFrn2ShLBobUJi5MJrdg7hUBf0owO3h8eM8BJD6fcn8oxT2WaaGFsFKPXA==
  template:
    metadata:
      name: gchat-notification
      namespace: flux-system
