apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgCNnskHS+noVwQ9qVDl5oPWcIAm3CjAVeAS2hHmnp11LQfXJhgv+SvXi6n/w/f3SKD92Ux2hN3qADeWyTJTr0UtuVzwlGQoYfs/yCJ6GQJXWXgR+Zka5HqLgdbPW494B/zR2DEEoOi3ZxxvGkwLVsyyQbLfuITtEv9R96GetV5yjR1tmGQjAIUtqeunMNZkIz95g5sTi5I5s2AqkPahnTqt2oIcgdkEJ7oCrl+Bhj80eFOF+tuDSDru3Vdk5cwyErKnBMWVjy5SD3yKJfy8dWaSbkNwXsrBlf3RRbKWstaK76x/3X3Fmtaij9449xJd5+XFVFNmkViVT0nljuPWYdHw/4KR4zz3PlnU8zJBmPOJH0eaWQs+65LzXWYKbqj4ocC8iGMEJ3iCcSoEl+7aaUm1vxvZ0imGKEs8lWtjHIv2bXzmgn9raf/oaooP6z8a+Yv7AzeCIps5HBFrsnH1xEoQv4IZva9G6jX5V5RPsL7VBVWWrrrGX/oXK8t3dzO+Z/39baJ1Xm4BftoUMesWrL6mnvHWSUdWXDY9rj5mLebvjGT9Ew1H8Qrb4gkv4ck2jMgWI6rzuPboho1zN+WDX39oRnQSD0ghEncKScvbc1c3YZ/YxUCLH2fvTcWsVBAmV4l1RGDPAg5NyRunj8WrbH71uq1VLOjDUbuZYY+ALIbtEoIcYziqDsOFzLgsSlw/15S7geT7xka/cZbKtTBe4HVdj8ta8ApooakfSPFY30NmGhoZY0zeF0Wh
  template:
    metadata:
      name: github-token
      namespace: flux-system

