apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: github-info
  namespace: flux-system
spec:
  providerRef: 
    name: github
  eventSeverity: info
  eventSources:
  - kind: Kustomization
    namespace: flux-system
    name: '*'
  suspend: false
