apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base/drawbridge
namespace: drawbridge-staging
patches:
- |-
    apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      name: drawbridge-tls-cert
    spec:
      commonName: store.staging.profian.com
      dnsNames:
      - store.staging.profian.com
