apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: steward
spec:
  rules:
  - host: attest.staging.profian.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: steward
            port:
              number: 8080
