apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wave
  namespace: flux-system
spec:
  releaseName: wave-controller
  targetNamespace: wave-controller
  chart:
    spec:
      chart: wave
      sourceRef:
        kind: HelmRepository
        name: wave-k8s
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
