apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  releaseName: cert-manager-controller
  targetNamespace: cert-manager
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  interval: 1h0m0s
  install:
    crds: Skip
  values:
    installCRDs: true
    extraArgs:
    - --enable-certificate-owner-ref
    global:
      leaderElection:
        namespace: cert-manager
    nodeSelector:
      "kubernetes.azure.com/mode": system
