apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: haproxy-ingress
  namespace: flux-system
spec:
  releaseName: haproxy-ingress-controller
  targetNamespace: ingress-controller
  chart:
    spec:
      chart: kubernetes-ingress
      sourceRef:
        kind: HelmRepository
        name: haproxytech
        namespace: flux-system
  interval: 1h0m0s
  install:
    crds: Skip
  values:
    controller:
      kind: DaemonSet
      ingressClassResource:
        default: true
      nodeSelector:
        "kubernetes.azure.com/mode": system
      config: {}
      logging:
        level: info
        traffic:
          address: stdout
          format: raw
          facility: daemon
      service:
        enabled: false
    defaultBackend:
      enabled: true
