apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: haproxy-ingress
  namespace: flux-system
spec:
  releaseName: haproxy-ingress-controller
  targetNamespace: ingress-controller
  chart:
    spec:
      chart: haproxy-ingress
      sourceRef:
        kind: HelmRepository
        name: haproxy-ingress
        namespace: flux-system
      version: "0.13.9"
  interval: 1h0m0s
  values:
    defaultBackend:
      enabled: true
    controller:
      kind: DaemonSet
      nodeSelector:
        "kubernetes.azure.com/mode": system
      ingressClassResource:
        enabled: true
      haproxy:
        enabled: true
      logs:
        enabled: true
      stats:
        enabled: true
      metrics:
        enabled: true
      service:
        # This service will not get used: we can't add multiple LB IPs, so we create the LB services manually.
        type: ClusterIP
