apiVersion: v1
kind: Service
metadata:
  name: haproxy-ingress-ipv4
  namespace: ingress-controller
spec:
  type: LoadBalancer
  loadBalancerIP: "0.0.0.0"
  externalTrafficPolicy: Local
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-80
    port: 80
    protocol: TCP
    targetPort: http
  - name: https-443
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/instance: haproxy-ingress-controller
    app.kubernetes.io/name: haproxy-ingress
  sessionAffinity: None
