apiVersion: v1
kind: Service
metadata:
  name: haproxy-ingress-ipv4
  namespace: ingress-controller
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: 0.0.0.0
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - appProtocol: http
    name: http
    port: 80
    protocol: TCP
    targetPort: http
  - appProtocol: https
    name: https
    port: 443
    protocol: TCP
    targetPort: https
  - name: stat
    port: 1024
    protocol: TCP
    targetPort: stat
  selector:
    app.kubernetes.io/instance: haproxy-ingress-controller
    app.kubernetes.io/name: kubernetes-ingress
  sessionAffinity: None
