apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: k8s-config
  path: ./infrastructure
  prune: true
  wait: true
  timeout: 1m
  patches:
  - target:
      kind: HelmRelease
      namespace: flux-system
      name: haproxy-ingress
    patch: |
      - op: replace
        path: /spec/values/controller/service/loadBalancerIP
        value: 52.191.102.158
