apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: k8s-config
  path: ./infrastructure
  prune: true
  patches:
  - target:
      kind: Service
      namespace: ingress-controller
      name: haproxy-ingress-ipv4
    patch: |
      - op: replace
        path: /spec/loadBalancerIP
        value: 52.191.102.158
