apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: storage-services
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
  - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: k8s-config
  path: ./storage/services/
  force: true
  prune: true
  wait: true
  timeout: 5m0s
