apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: drawbridge
  app.kubernetes.io/name: drawbridge
resources:
- certificate.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
